#+TITLE: Harnack Inequalities and Ancient Solutions
#+BEAMER_HEADER: \subtitle{Mission Beach\\Joint with Mohammad Ivaki and Julian Scheuer}
#+AUTHOR: Paul Bryan
#+EMAIL: pabryan@gmail.com
#+DATE: May 2017

#+SETUPFILE: ~/.emacs.d/org-templates/bibliography.org

#+OPTIONS: H:2 toc:t
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation]
#+BEAMER_THEME: Boadilla
#+LaTeX_HEADER: \AtBeginSection[]{\begin{frame}\frametitle{Table of Contents}\tableofcontents[currentsection]\end{frame}}

#+LaTeX_HEADER: \input{local_definitions}

* Hypersurface Flows
** Hypersurface Flows
- \((N^{n+1}, \bar{g})\) = Riemannian or Lorentzian Manifold.
- \(M^n\) = compact manifold (except in Minkowski space - more later)\pause
- \(M_t = X_t(M)\) is smooth family of embedded hypersurfaces where \(X_t : M \to N\) satisfies
  \[
  \partial_t X_t = -F(\mathcal{W}_t) \nu_t
  \]
  \pause
  - \(\mathcal{W}_t\) = Weingarten extrinsic curvature, \(\nu_t\) = Unit Normal.
  - \(F\) = /curvature function/ = smooth, symmetric function of principal curvatures (geometric flow), increasing in each argument (parabolic).\pause
- Assumption: \(M_t\) is /spacelike/: induced metric \(g_t = X_t^{\ast} \bar{g} > 0\). \pause
- Assumption: strict convexity: 
  \[
  h(X, X) := g(\mathcal{W}(X), X) > 0 \quad \forall X \ne 0 \in TM \Leftrightarrow \kappa_i > 0.
  \]\pause
- Assumption: \(\abs{F} > 0\) for \(\kappa_i > 0\).
** Examples of Hypersurface Flows
- Mean Curvature Flow: \(F(\mathcal{W}) = H = \Tr(\mathcal{W}) = \kappa_1 + \cdots + \kappa_n\).
- Inverse Mean Curvature Flow: \(F(\mathcal{W}) = -H^{-1} = - \Tr(\mathcal{W})^{-1} = -\frac{1}{\kappa_1 + \cdots + \kappa_n}\).
- Gauss Curvature Flow: \(F(\mathcal{W}) = K = \Tr(\wedge^n \mathcal{W}) = \kappa_1 \cdots \kappa_n\). \pause
- Elementary Symmmetric Polynomials: \(F(\mathcal{W}) = \sigma_k = \Tr(\wedge^k \mathcal{W}) = \sum_{i_1 < \cdots < i_k} \kappa_{i_1} \cdots \kappa_{i_k}\).
- Power sums: \(F(\mathcal{W}) = P_k = \Tr(\mathcal{W}^k) = \kappa_1^k + \cdots + \kappa_n^k\). \pause
- New functions from old
  - Take powers: \(H^p\), \(K^p\), \(\sigma_k^p\), etc.
  - Symmetric polynomials in \(\kappa_i\) = Polynomials in \(\sigma_k\) = Polynomials in \(P_k\)
  - Transcendental functions, e.g. \(\exp(H)\)
** Examples of Hypersurface Flow
- Any smooth function \(f\), increasing in each argument: \(F(\mathcal{W}) = f(\sigma_1, \cdots, \sigma_n)\)
- Such functions give parabolic flows. \pause
- For Harnack inequalities (and many other results!) need to assume either
  - \(f\) is convex,
  - \(f\) is concave,
  - \(f\) is inverse concave (i.e. \(\mathcal{W} \mapsto 1/f(\mathcal{W}^{-1})\) is concave) or inverse convex.
  - \(f = \operatorname{sgn}(p) f_1^p\) where \(f_1\) is \(1\)-homogeneous.
   \pause
- Remark from classical invariant theory:
  - A theorem of Weyl says any polynomial function of \(\mathcal{W}\) invariant under change of coordinates must be a polynomial in \(\sigma_k\). Trace is the only invariant, linear polynomial, etc.
  - Approximating smooth \(F\) by polynomials \(\Rightarrow\) only invariant smooth functions are of the form \(f(\sigma_1, \cdots, \sigma_n)\).
* Review of Harnack Inequalities and Ancient Solutions
** Li-Yau-Hamilton and Moser Harnack Inequality
- Li-Yau-Hamilton (Andrews in this context!): \pause
  - The speed \(F\) evolves by a scalar parabolic equation.\pause
  - Let \(u = \partial_t \ln \abs{F} = \tfrac{\partial_t F}{F}\).
    \[
    \partial_t u - \abs{\nabla u}_h^2 \geq -\frac{p}{p+1} \frac{1}{t}
    \]\pause
  - \(\abs{\nabla u}_h^2 = h(\grad_h u, \grad_h u)\) where \(du(X) = h(\grad_h u, X)\) defines the gradient of \(u\) w.r.t. \(h\). \pause
- Moser:
  \[
  F(x_1, t_1) \leq C(x_1, x_2, t_1, t_2) F(x_2, t_2)
  \]
  with \(0 < t_1 < t_2\). \pause
- Li-Yau-Hamilton \(\Leftrightarrow\) Moser by integrating over space-time paths (sharpest C):
  \[
  C = \left(\frac{t_2}{t_1}\right)^{\tfrac{p}{p+1}} e^{\Delta/4}
  \]
  - \(\Delta = \inf_{\gamma} \int_{t_1}^{t_2} \tfrac{1}{F} h(\gamma', \gamma') dt\) for \(F > 0\) and \(\gamma(t_1) = x_1, \gamma(t_2) = x_2\).
  - Replace \(\inf\) by \(\sup\) for \(F < 0\).
** Why Care About Harnack inequalities?
- Regularity: e.g. Moser proved divergence form + measurable coefficients \(\Rightarrow\) \holder{} continuity. \pause
- Bootstrapping: \(C^{k,\beta}\) coefficients \(\Rightarrow\) \(C^{k+1,\alpha}\) continuity.\pause
  - Heuristic example
    \[
    \partial_t u = a u'' + b u' + c u + d
    \]
    with \(a,b,c,d \in C^{k,\beta}\) \pause
  - Evolution of gradient
    \[
    \partial_t u' = (\partial_t u)' = a (u')'' + (a' + b) (u')' + (b + c) u' + c' u  + d'
    \]
    with \(C^{k-1,\beta}\) coefficients.\pause
  - Repeat \(k+1\) times to get \(C^{-1,\beta}\) \(\sim\) measurable coefficients.
  - Therefore \(u^{(k+1)} \in C^{\alpha}\)!
** Why Care About Harnack inequalities?
- Singularity analysis: Blow ups of singularities are solitons (sharp case in the Harnack!) \pause
- Uniform parabolicity: e.g. GCF \(F = K\).\pause
  - \(\kappa_i = 0\) for some \(i\) \(\Rightarrow F = 0, dF = 0 \Rightarrow\) the flow is degenerate parabolic.\pause
  - Upper bounds for the speed are easiest: \(K \leq K_0(t)\) (Tso)\pause.
  - Moser Harnack: \(0 \leq \sup_{x\in M} F(x, t_1) \leq C \inf_{x\in M} F(x, t_2)\)
  - Therefore, if \(\kappa_i = 0\) at \(t = t_2\), then \(F \equiv 0\), \(t \leq t_2\) (provided \(C\) bounded!) (compare strong maximum principle)\pause
  - Li-Yau-Hamilton \(\Rightarrow\) convexity is preserved while the flow is smooth:
    \[
    t^{-p/(p+1)} \partial_t (t^{p/(p+1)}F) = \partial_t F + \frac{p}{p+1} \frac{1}{t} F \geq \frac{1}{F} \abs{\nabla F}_h^2 \geq 0.
    \]\pause
    - Therefore \(t^{p/(p+1)}F\) is increasing and so \(F(\cdot, 0) > 0 \Rightarrow F(\cdot, t) > 0\).
** Why Care About Ancient Solutions?
- Ancient solutions exist for \(t \in (-\infty, T)\).\pause
- Since parabolic equations are smoothing forwards in time, they get worse backwards in time!
- Only very special solutions extend back to \(-\infty\) and may reflect symmetries of the flow and lend intuition. \pause
- Blow-ups of singularities produce ancient solutions:
  - \(\sup_{x\in M} \|A(x, t)\|^2 \to \infty\) as \(t \to T\):\pause
  - For \(\lambda_k \to \infty\):
  \[
  \sqrt{\lambda_k} g(T + \frac{t}{\sqrt{\lambda_k}}) \quad t \in (-\sqrt{\lambda_k} T, 0)
  \]
  converges to an ancient solution as \(k \to \infty\). \pause
  - Type II + Harnack inequality \(\Rightarrow\) the ancient solution is a translating soliton.
  
** Heat Equation Harnack
- \(f : M \times [0, T) \to \RR\), \(M\) compact \(\ric > 0\).
\[
\partial_t f = \Delta f, \quad f > 0
\]\pause
- Let \(u = \ln f\).
- \(f(x_1, t_1) \leq C f(x_2, t_2)\) iff \(u (x_2, t_2) -  u(x_1, t_1) \geq -\ln C\) \pause
  #+BEGIN_latex
  \[
  \begin{split}
  u(x_2, t_2) - u(x_1, t_1) &= \int_{t_1}^{t_2} \dd{t} \left[u(\gamma(t), t)\right] dt \\
  &= \int_{t_1}^{t_2} \partial_t u + d u \cdot \gamma'
  \end{split}
  \]
  #+END_latex
  where \(\gamma(t_1) = x_1\) and \(\gamma(t_2) = x_2\).
** Heat Equation Harnack
- Sharpest Harnack - estimate the integrand:
  \[
  \partial_t u + du \cdot \gamma' \geq \partial_t u - |\grad u|^2 - \frac{1}{4} |\gamma'|^2
  \]\pause
- Equality if and only if \(\gamma' = -2 \grad u\) by polarisation Cauchy-Schwarz:
  #+BEGIN_latex
  \[
  \begin{split}
  0 &\leq g(\grad u + \tfrac{1}{2} \gamma', \grad u + \tfrac{1}{2} \gamma') = g(\grad u, \grad u) + \frac{1}{4} g(\gamma', \gamma') + g(\grad u, \gamma') \\
  &= g(\grad u, \grad u) + \frac{1}{4} g(\gamma', \gamma') + du (\gamma')
  \end{split}
  \]
  #+END_latex
  \pause
- Reparametrise to track steepest descent:
  \[
  \tilde{u}(x, t) = u(\varphi_t(x), t), \quad \partial_t \varphi_t = - \grad u(\varphi_t)
  \]\pause
- Li-Yau Harnack
  \[
  \partial_t \tilde{u} \geq -\frac{n}{2} \frac{1}{t}
  \]
** Proving Li-Yau
With reparametrisation:
- Let \(\tilde{Q} = \partial_t \tilde{u} = \Delta_{g_t} \tilde{u}\)
- Show
  \[
  \partial_t \tilde{Q} \geq \Delta_{g_t} \tilde{Q} + g_t(\nabla \tilde{Q}, \nabla \tilde{u}) + \tfrac{2}{n} \tilde{Q}^2
  \]
  where now \(g_t = \varphi_t^{\ast} g\) is time-dependent. \pause
- Maximum principle completes the proof. \pause
- Note to compute \((\partial_t - \Delta_{g_t}) \tilde{Q}\) need to compute \([\partial_t, \Delta_{g_t}]\). \pause
Without reparametrisation:
- Let \(Q = \partial_t u - |\nabla u|^2 = \Delta Q\). \pause
- Show
  \[
  \partial_t Q \geq \Delta Q + g (\nabla Q, \nabla \tilde{u}) + \tfrac{2}{n} Q^2
  \]\pause
- This time \([\partial_t, \nabla] = 0\) but need to use Bochner formula for \(\Delta |\nabla u|^2\)
* Harnack Inequalities for Hypersurface Flows
** Reparametrisation
- Same idea of tracking steepest descent works for hypersurface flows: \pause
  \(\tilde{X}(x, t) = X(\varphi_t(x), t), \quad \partial_t \varphi_t = - \grad_h F (\varphi_t)\).
  \(\partial_t \tilde{X} = -F(\tilde{W}) \tilde{\nu} - \grad_{\tilde{h}} F(\tilde{W})\). \pause
  - The speed \(\xi = -F(\tilde{W}) \tilde{\nu} - \grad_{\tilde{h}} F(\tilde{W})\) is a /transverse vector field/.\pause
- Geometric Properties:
  - \(\partial_t \nu = 0\) \pause
  - \(\nabla_t g = 0\) where 
    \[
    \nabla_t Z = \bar{\nabla}_{\partial_t \tilde{X}} Z = \bar{\nabla}_Z \xi = -\mathcal{A} (Z)
    \]
    is the /affine shape operator/ \(\mathcal{A}: TM \to TM\).
  - Here \(\bar{\nabla}\) is the ambient Levi-Civita connection. \pause
- \(\partial_t \nu = 0\) used by Chow to study GCF solitons. \pause
- Andrews works with the Gauss map parametrisation in Eulidean space:
  - Fixed normal and fixed metric.
  - Tremendous simplification of the long calculations of Hamilton and Chow!
** Solitons
- \(X(x, t) = \lambda(t) X_0(x)\) with \(N = \RR^{n+1}\).
- Solves the curvature flow provided \(\ip{\partial_t X}{\nu} = -F(\mathcal{W})\).\pause
- Then \(\partial_t X = -F\nu - \grad_h F\)
- Solitons evolve exactly by the reparametrisation! \pause
- Question: In the reparametrisation, why do we use \(\grad_h F\) and not say \(\grad_g F\)? \pause
  - Answer one: The evolution of \(F\) depends on \(h\) and we expect it must play a role. Everything works out with \(\grad_h F\) but not \(\grad_g F\) (presumably!)\pause
  - Answer two: For solitons we have equality:
    \(Q = \partial_t \ln |F|\)
    \[
    \partial_t Q = \Delta Q + T \ast Q + \tfrac{p+1}{p} Q^2
    \]\pause
  - Answer three: The normal is static precisely under the reparametrisation.
** Harnack Inequalities
** Proof
** Duality
* Ancient Solutions of  Hypersurface Flows
** Existence and (lack of) Uniqueness
** Convex Ancient Solutions are Rare!
** Classification by Monotone Functions
** Degree One Homogeneity in the sphere
** Arbitrary Flows in the Sphere
